### ISSUE TITLE
Bug in Kuiper ?

### ISSUE THREAD

**Issue by ISorokos** [ISorokos/SafeML#11]
https://github.com/ISorokos/SafeML/blob/613bc2250d430e098169988e0ddd9ae2940e385d/Implementation_in_Python/KuiperDistance.py#L30

@koo-ec is this line correct ?
Shouldn't the height be compared to down instead ?

**Comment by koo-ec** [comment]
Thanks for the comment. Yes, you are right. the height should be compared with down instead. I corrected it.
