### ISSUE TITLE
Issue: Return statements in the 'Implementation_in_Python' statistical distance measure methods are outside the scope of the method.

### ISSUE THREAD

**Issue by WillBridges1999** [ISorokos/SafeML#7]
**Describe the bug**
The statistical distance measure methods have the return statement outside of the method scope (they just need tabing over by 1).

**To Reproduce**
1. Go to 'Implementation_in_Python'
2. Click on 'CVM_Distance.py'
3. Scroll down to 'CVM_Dist method's return statement' (or any others)

**Expected behavior**
Returns the values wanted, without a 'return statement' error.

**Screenshots**
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/62393241/109190609-2896d600-778d-11eb-822b-d122c632d07d.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/62393241/109190707-482dfe80-778d-11eb-8fd9-302f38794762.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by koo-ec** [comment]
I have updated all functions. The problem fixed by putting a few spaces before the return.
